resolver: lts-7.15
packages:
- '.'
extra-deps:
- X11-xft-0.3.1
- xmonad-contrib-0.12
- xmonad-extras-0.12.1
# Override default flag values for local packages and extra-deps
flags:
  xmonad-extras:
    with_hint: false
    with_mpd: false
extra-package-dbs: []
